### ISSUE TITLE
Seems to be missing any meson.build files?

### ISSUE THREAD

**Issue by ericonr** [mesonbuild/raylib#1]
https://github.com/mesonbuild/raylib/tree/2.6.0 seems to be missing all the necessary files?

I have a working version for raylib 4.0.0 in https://github.com/ericonr/raylib-meson, would be happy to make a PR to adapt it into this repo, if there's interest (and become a maintainer, if desired).

**Comment by jpakkane** [comment]
These repositories are obsolete and no longer used. Nowadays everything is under the `mesonbuild/wrapdb` repo, please file your PRs against that one. Thanks.

**Comment by ericonr** [comment]
Thanks! Might be nice to archive the repository?
